### ISSUE TITLE
Relative paths when specifying .tpr file not working

### ISSUE THREAD

**Issue by MSiggel** [bio-phys/MDBenchmark#120]
When specifying ```--name ../npt.tpr``` the file is not properly processed and not copied to the benchmark folder leading to failure of mdbenchmark submit

**Comment by mimischi** [comment]
So the problem is the following: Having a `md.tpr` file in the parent directory and running `mdbenchmark generate --name ../md.tpr --host draco --module gromacs/123`, do several things:

1) It will write the category `name` as `../md`.
2) It will copy the file to `draco_gromacs/123/1/../md.tpr`.

```bash
.
└── draco_gromacs
    └── 123
        ├── 1
        │   └── bench.job
        ├── 2
        │   └── bench.job
        ├── 3
        │   └── bench.job
        ├── 4
        │   └── bench.job
        ├── 5
        │   └── bench.job
        └── test.tpr

7 directories, 6 files
```
