### ISSUE TITLE
Updating Travis

### ISSUE THREAD

**Issue by mimischi** [bio-phys/MDBenchmark#149]
We are currently running unit tests on macOS. Is there any need for these? This is the slowest test on Travis-CI and I wonder whether there is any usecase for MDBenchmark on macOS? What do you think @kain88-de?

Looking at our download statistics for version 2.0.0 (2019-05-22), the macOS downloads account for only 2.2%:

System | Downloads | Percentage
------------ | ------------- |  ------------- 
Linux | 2216 | 97.8
macOS | 51 | 2.2
Total | 2267 | 100.0

<img width="685" alt="grafik" src="https://user-images.githubusercontent.com/1052860/58154585-43602080-7c72-11e9-8956-830c00bf0c43.png">

**Comment by kain88-de** [comment]
later analysis is certainly done on osx. We do not use our own c extensions here. So you can skip them if you like.

**Comment by mimischi** [comment]
Will be resolved by #151. We can now run Python 3 tests on macOS with Travis-CI!
