### ISSUE TITLE
Install receipes failed on cluster draco 

### ISSUE THREAD

**Issue by lukas-stelzl** [bio-phys/MDBenchmark#15]
**Expected behavior**

installation of the package

**Actual behavior**

Fails with error messages:

`lustelzl@draco02:~/library>  conda install -c conda-forge mdbenchmark
Fetching package metadata .............

PackageNotFoundError: Packages missing in current channels:
            
  - mdbenchmark

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
            

lustelzl@draco02:~/library> `

`lustelzl@draco02:~/library> pip install mdbenchmark --user

    running build_ext
    building 'Levenshtein._levenshtein' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/Levenshtein
    x86_64-conda_cos6-linux-gnu-gcc -pthread -fno-strict-aliasing -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/mpcdf/soft/SLES122/common/anaconda/2/5.0.0/include/python2.7 -c Levenshtein/_levenshtein.c -o build/temp.linux-x86_64-2.7/Levenshtein/_levenshtein.o
    unable to execute 'x86_64-conda_cos6-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/mpcdf/soft/SLES122/common/anaconda/2/5.0.0/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1XE6U1/python-Levenshtein/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4Wejev-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-1XE6U1/python-Levenshtein `

**Currently version of MDBenchmark:**

Lastest version from Github

(run `mdbenchmark --version"`)

**Comment by kain88-de** [comment]
Yeah the package isn’t on co da forge yet. Sorry I did t take out the install description yet.

**Comment by kain88-de** [comment]
Works now.
