### ISSUE TITLE
Ideal scaling for benchmark plots

### ISSUE THREAD

**Issue by jkoefinger** [bio-phys/MDBenchmark#178]
**Expected behavior**

Ideal scaling should go through origin and first node

**Actual behavior**

Ideal scaling should goes through first and second node

**Your version of MDBenchmark:**

(run `mdbenchmark --version` on your machine)

**Comment by ksebaz** [comment]
@jkoefinger  if you want to test, #193 now contains the new scaling projection. It looks like this: [foo](https://github.com/bio-phys/MDBenchmark/files/10686740/foo.pdf). Is that as you intende?

**Comment by balazsfabian** [comment]
@ksebaz, #193 indeed produces the [correct scaling](https://github.com/bio-phys/MDBenchmark/files/10754200/my_benchmark_results.pdf)
