### ISSUE TITLE
Extend Plotting options

### ISSUE THREAD

**Issue by kain88-de** [bio-phys/MDBenchmark#24]
Our plotting option is limited right now. It would be nice if we can extend to allow plotting with several gromacs versions.  The general roadmap for this would be.

- [x] factor out plotting from `analyze`
- [x] have function that can add a line plot for one benchmark run (gromacs version/host/gpu)
- [x] maybe have a new command `mdbenchmark plot` that takes a csv from as input.
- ~[ ] suggest which number of nodes have the best performance~

**Comment by MSiggel** [comment]
the same principle should also be implemented to differentiate different md engines like namd and gromacs for sake of easy comparisons.

**Comment by kain88-de** [comment]
The interface of the function to plot a single benchmark (same module, same system, etc) should have the following API. 

```python
def plot_single_benchmark(..., ax=None):
    if ax is None:
        ax = plt.gca()
    ...
    return ax
```

This gives convenience for plotting as a library as well as full control if someone wants to create more complicated plots.

**Comment by kain88-de** [comment]
The plotting options should probably take an argument `groupby` that takes a list of variables that we want to separate for the plotting. So that e.g.

```bash
mdbenchmark plot results.csv --groupby="gpu, module, host"
```
Will produce a line for each unique combination of values in the `gpu`, `module` and `host` columns.
The current default is then `--groupby="gpu"`.  This allows to be flexible in the allowed graphs that can be produced with a minimal UI. Your code should catch column names like `nodes` or `ns/day` to be invalid for a groupby option because those are used for the x and y axis.

In the code this should look similar to

```python
cols = groupby.split(',')
# This should generate an iterable of dataframes for each unique combination of
# the provided cols.
runs = dataframe.groupby(cols)
for df in runs:
    plot_single_benchmark(df, ax=ax, ...)

```

This means we support and an arbitrary number of lines to the plot. This, of course, opens the question about colors. We can actually let matplotlib deal with that.

```python
# plot measured results
p = ax.plot(x, y)
# obtain last used color object.
c = p[0].get_color()
# plot performance fit in same color
ax.plot(x, y, color=c)
```

**Comment by mimischi** [comment]
As a note, so we do not forget about this:

If for whatever reasons performance from some nodes is not available (skipped benchmarks with `n`-nodes, benchmark has not yet finished, ...), the plotting is not 100% reliable. Using the current `mdbenchmark version 1.2.0` release, this happens:

```bash
mdbenchmark analyze
WARNING	We were not able to gather informations for all systems.
	Systems marked with question marks have either crashed or
	were not started yet.
                     gromacs  nodes  ns/day  run time [min]    gpu host ncores
0   gromacs/2016.4-plumed2.3      1  13.106              15  False  xxx     20
1   gromacs/2016.4-plumed2.3      2  25.541              15  False  xxx     40
2   gromacs/2016.4-plumed2.3      3  33.204              15  False  xxx     60
3   gromacs/2016.4-plumed2.3      4  45.827              15  False  xxx     80
4   gromacs/2016.4-plumed2.3      5  57.922              15  False  xxx    100
5   gromacs/2016.4-plumed2.3      6  64.466              15  False  xxx    120
6   gromacs/2016.4-plumed2.3      7  75.707              15  False  xxx    140
7   gromacs/2016.4-plumed2.3      8       ?              15  False  xxx      ?
8   gromacs/2016.4-plumed2.3      9  91.348              15  False  xxx    180
9   gromacs/2016.4-plumed2.3     10  96.571              15  False  xxx    200
10  gromacs/2016.4-plumed2.3     11       ?              15  False  xxx      ?
11  gromacs/2016.4-plumed2.3     12       ?              15  False  xxx      ?
12  gromacs/2016.4-plumed2.3     13       ?              15  False  xxx      ?
13  gromacs/2016.4-plumed2.3     14       ?              15  False  xxx      ?
14  gromacs/2016.4-plumed2.3     15       ?              15  False  xxx      ?
15  gromacs/2016.4-plumed2.3     16       ?              15  False  xxx      ?
```

![runtimes](https://user-images.githubusercontent.com/1052860/36909071-53ed0f2e-1e3d-11e8-9c5a-b8e454dc4950.png)

Note how the performance on 9 and 10 nodes is shifted down by one place to the left, while the number of cores/node is correct. We should make sure to address this issue in the new implementation.
