### ISSUE TITLE
benchmarking procedure improvements sugestions

### ISSUE THREAD

**Issue by pszi1ard** [bio-phys/MDBenchmark#44]
**Expected behavior**
I/O, load balancing, CPU/GPU throttling and other performance influencers need to be accounted for by using timer resetting.
See Benchmarking procedure section of [10.1002/jcc.24030](http://onlinelibrary.wiley.com/doi/10.1002/jcc.24030/full)

**Actual behavior**
Timer seems to never be reset.

**Your version of MDBenchmark:**
(run `mdbenchmark --version` on your machine)

**Comment by mimischi** [comment]
Thanks for the heads up! We actually talked about this, but it somehow never made it into the job files.

As far as I see it adding `-resethway` to the `mdrun` command [here](https://github.com/bio-phys/MDBenchmark/blob/master/mdbenchmark/templates/draco#L35) and [here](https://github.com/bio-phys/MDBenchmark/blob/master/mdbenchmark/templates/hydra#L22) should be sufficient, is that correct?

**Comment by kain88-de** [comment]
@pszi1ard 
 Thank you for the suggestion, 

Do you have an experience for which systems the counter reset would make a difference? On my simulations of ~50000 atoms I usually see a variability of 5-10 ns for a 24h long run on the same cluster, I assume at 24h runtime any influence of the initial load balancing and other influencers is negligible.  When we decided the for 15min runtime of benchmarks we initially tested run times from 5min to 6h to see if there is any influence of runtime on the result. For these runs, we didn't notice that the variability of the reported performance exceeds  3 ns. This means we don't see that anything influences our measurements when we run for 15min. 

A reason for this is that with 15min runtime and 100 ns/day we accumulate around 1 million steps.  If only the first 10k-50k steps are affected this should make them negligible in the final result.

**Comment by pszi1ard** [comment]
@mimischi Short answer: yes. (WIth the side-note that it depends how long are your runs and what you run on.)

Note that if you want to minimize the time/run e.g. to scan a large parameter space in hours rather than days, you can run short as performance typically stabilizes within a few hundred to thousand iterations. That does not account for longer-term effects like temperature-induce clock throttling of GPUs (or CPUs). Additionally, in more recent versions, mdrun won't report performance (or even err out) if the reset happens during the PP-PME load-balancing. For that reason, short runs can also fail due to to early reset. In these cases you can still play with `-resetstep` and reset beyond the "halfway", but that might not be wroth the hassle.

On the other hand, if you run at least for a few minutes/run, a `-resethway` will be quite adequate.

All that said, we are planning to revamp the benchmarking-oriented built-in functionality in GROMACS because mdrun is generally in a better position to know when should it be safe/reliable to start timing in a benchmark run (e.g. after some load-balancing has completed). Feedback and suggestions (or even code ;) is welcome!

**Comment by pszi1ard** [comment]
@kain88-de If you run 15 minutes long benchmarks, resetting should not have a significant impact except in cases where some parameter converges slowly, initialization/startup takes unreasonably long, or the simulated system happens to undergo changes that lead to performance variation (e.g. protein tilting changing domain decomposition and load balance).
That said, 15 minutes can also be too long as it means that scanning a few values of a few parameters parameters can end up taking tens of hours to complete. Besides costing a lot, if you do that on an HPC machine with a shifting job environment/neighbors, you might end up comparing runs that were done many hours apart with entirely different node/rack "microclimate" (which can have a significant impact e.g. on 3D-FFT performance).
Therefore, I'd recommend always designing the benchmarks to have a run-time that allows measuring what you want to measure, not less and not more.

**Comment by kain88-de** [comment]
> That said, 15 minutes can also be too long as it means that scanning a few values of a few parameters can end up taking tens of hours to complete.

Currently, we use the tool to decide on the number of nodes used to run a simulation on. I usually have around 10 benchmark runs that finish in about 1-2 hours. But I agree that we can optimize the runtime. I opened a new issue #50 for this so we keep track of it. 

More *micro* optimization should be done can be done with gromacs once one has a rough understanding of the number of nodes needed. I actually tried to use `tune_pme` to optimize settings. Even with large systems ~1M atoms on up to 10 nodes, I didn't see a significant performance difference in the standard settings it tried.. Having better performance benchmarking in gromacs would definitely help to understand why this happens.

**Comment by mimischi** [comment]
Resurrecting this issue.

@pszi1ard just a quick question: GROMACS 2019 deprecated support of `gmx grompp -resethway`, but `gmx benchmark` has not been implemented yet. Is the former functionality gone completely? If so, is there a different way to use 2019 for proper benchmarking? We're currently doing some benchmarks with `-resethway` in 2018.

**Comment by pszi1ard** [comment]
Deprecation only means that the flag will be removed in a future release. As long as no alternative has been provided, you can use both -resethway/-resetstep.

**Comment by mimischi** [comment]
This is now implemented in the `version-3` branch. Closing the feature for now.
