### ISSUE TITLE
Generate Function Arguments

### ISSUE THREAD

**Issue by MSiggel** [bio-phys/MDBenchmark#47]
Currently we generate individual datreants and folders with 
```python 
def write_bench(top, tmpl, nodes, gpu, module, tpr, name, host, time):
```
the `tpr` argument is very gromacs specific and should be removed in the future once NAMD is implemented. It currently does not impair the code but is unused in the when running this for NAMD.

**Comment by mimischi** [comment]
The `tpr` argument was only added recently. We pass the name of the corresponding tpr file to `write_bench`, after ensuring that it actually exists. In regards to #29: we could already solve this issue in there.
