### ISSUE TITLE
add example of scaling plot

### ISSUE THREAD

**Issue by kain88-de** [bio-phys/MDBenchmark#5]
It would be nice to have an example plot (pdf) showing the performance scaling. They look really good thanks to @mimischi. Then we can also add documentation how we determine the ns/day.

**Comment by mimischi** [comment]
That's a good idea. Maybe we could use that one plot of yours with the soluble domain in water, higher performance looks nicer 🔥

Also I was thinking we could add a small 'usage video' to the README, to catch the users eye. Some small GIF that quickly goes over the commands and the results, i.e. like [the one](https://github.com/kennethreitz/pipenv/blob/master/README.rst#pipenv-python-development-workflow-for-humans) for `pipenv`.
