### ISSUE TITLE
adjust benchmark time by system size

### ISSUE THREAD

**Issue by kain88-de** [bio-phys/MDBenchmark#50]
Generally, we will have a hard time to do dynamic adjustments of the runtime depending on the system size, since a lot of factors can influence performance. But GROMACS prints the number of steps used in a simulation and we can set a minimum number of steps we require for good results. 

Which number would be good as a minimum for the steps? The gromacs benchmarks papers use 20k. I still have seen PME tuning up to 50k steps. So my guess would be 100k steps would be a good minimum. On GROMACS we can set this with `-nsteps=100000` when we start the simulation independent of the settings in the *tpr* file. Then we can also meaningfully reset the performance counters, see #44 

To give a feeling what this means for runtime. With a 2fs timestep to reach 100k steps in 15 minutes, we need a performance of ~20+ ns/day. 

I'm not sure how much NAMD does here and if it works better for shorter runs.

**Comment by pszi1ard** [comment]
> I still have seen PME tuning up to 50k steps. 

That's strange, it must have been a very "noisy" machine. Got the output, how much does the MFlops value the tuning prints?

**Comment by kain88-de** [comment]
[gist](https://gist.github.com/kain88-de/cffc67ae551ec23be633670a6323d54e)

Here are two log files for different systems. ~50K and ~1M atoms. In both cases the dynamic load balancing is set to `auto` and activates again well after 10k steps. The run command was in both cases `mpiexec -n $ncores mdrun_mpi -v -maxh 0.25 -deffnm md`. It isn't clear to me from the output where to look for things that would be most beneficial for performance tuning.

**Comment by mimischi** [comment]
We will be keeping the 15 minutes default for now. Users can always adjust the time necessary. We might put some information in the documentation.
