### ISSUE TITLE
add DOI citation

### ISSUE THREAD

**Issue by kain88-de** [bio-phys/MDBenchmark#6]
https://guides.github.com/activities/citable-code/

**Comment by mimischi** [comment]
Will you be doing this or when anyone of us two has time to?

**Comment by kain88-de** [comment]
I'll do it likely on sunday. We first need  a release (also something I
do on sunday)

Michael Gecht writes:

**Comment by kain88-de** [comment]
I setup everything on zenodo. With the next release we get a DOI. Right now I can make a manual upload but it only allows me to choose a CC license and not the GPL.
