### ISSUE TITLE
Run with different OpenMP/MPI configurations

### ISSUE THREAD

**Issue by kain88-de** [bio-phys/MDBenchmark#60]
Performance can be hugely influenced by the composition of MPI processes to OpenMP threads in gromacs and other engines. For this, it would be helpful to allow setting the ratio of OpenMP threads to MPI processes. Currently, we limit the number of MPI processes to the number of cores. So an option should select the ratio of hardware cores to MPI processes. Take the following mock command.

`mdbenchmark generate .... --core_to_mpi_ratio= 1 2 4 8`

With this, we set up 4 simulations. The ratio is defined as `nprocesses = ncores / ratio`. So for a machine with 24 cores and a ratio of 2, we would use 12 MPI processes. For an equal division, a ratio value should be a power of 2. I'm open for better names to this flag.

Also good would be an option to set up a run without MPI only using OpenMP on a single node.

**Comment by mimischi** [comment]
This is now implemented in the `version-3` branch.
