### ISSUE TITLE
Case sensitive modules

### ISSUE THREAD

**Issue by brisvag** [bio-phys/MDBenchmark#61]
When trying to generate the benchmark for GROMACS, I get the following error:

`ERROR There is currently no support for 'GROMACS'. Supported MD engines are: gromacs, namd.`

I suspect the problem is simply the fact that on this specific cluster the gromacs modules are in capitals:
e.g. `GROMACS/2016.1-foss-2016a-CUDA-7.5.18-avx2-hybrid` instead of the (likely) expected `gromacs/2016.1-foss-2016a-CUDA-7.5.18-avx2-hybrid`.

mdbenchmark version 1.3.0

**Comment by kain88-de** [comment]
Thanks for notifying us. A fix should be in the master branch soon.

**Comment by mimischi** [comment]
@brisvag [Version 1.3.1](https://github.com/bio-phys/MDBenchmark/releases/tag/version-1.3.1) has fixed this and it's out now on [PyPi](https://pypi.org/project/mdbenchmark/#description) and [conda-forge](https://anaconda.org/conda-forge/mdbenchmark/)!
