### ISSUE TITLE
indicate format (reST) for long description in setup.py

### ISSUE THREAD

**Issue by kain88-de** [bio-phys/MDBenchmark#63]
We might need to update the setup.py for proper reST display before the next release.

See: https://github.com/MDAnalysis/mdanalysis/issues/1837

**Comment by mimischi** [comment]
Do we need to do this? Version 1.3.0 was released after the markdown support was added and the page does look alright: https://pypi.org/project/mdbenchmark/

**Comment by kain88-de** [comment]
Pmda was released a couple of days ago and had problems. So I assume we could need it.
