### ISSUE TITLE
Lower default benchmarking time

### ISSUE THREAD

**Issue by mimischi** [bio-phys/MDBenchmark#91]
We currently use 15 minutes as the default time for benchmarks. GROMACS suggest to use a specific number of steps (10000?) and the option `-resethway` for benchmark runs.

@kain88-de You have done some benchmarking with different times. Do you have the plot comparing different run times / steps? And any informations on the systems used?

@MSiggel Do you know if there is an equivalent to this for NAMD?

**Comment by MSiggel** [comment]
@mimischi In NAMD the benchmarking info is always written after 500 steps not at the end of the simulation. so we could probably cut the required time down significantly

**Comment by kain88-de** [comment]
See #50

**Comment by kain88-de** [comment]
@MSiggel is there a way to find out if the required time was to short?

**Comment by MSiggel** [comment]
@kain88-de if the time is too short the log file will be missing the BENCHMARK line. This might happen if the time on the cluster was too short

**Comment by mimischi** [comment]
Can we ever assume that 10000 steps will be completed in a reasonable amount of time (<15 minutes) across all currently feasible system sizes?

**Comment by MSiggel** [comment]
maybe we could have a recommended time based on what we know from some of our existing systems and give an info for the user? something like < 100000 atoms use x minutes < 500000 use x etc. ... this way the user could be helped to make a halfway decent guess.
Or we warn that the default will only be valid to a certain size.

**Comment by kain88-de** [comment]
1_000_000+ atoms will take longer. Even on our own clusters.

**Comment by kain88-de** [comment]
not sure we can make a good guess for the whole range of hardware that is
used. What takes a minute on our cluster might take much longer on others.
So a rule of thumb could be to say the job can might need more time when
more then 500_000 atoms are used.

**Comment by mimischi** [comment]
Closing as well for now. We are keeping 15 minutes of benchmark time as default.
