### ISSUE TITLE
Switch to datreant from mdsynthesis

### ISSUE THREAD

**Issue by kain88-de** [bio-phys/MDBenchmark#99]
This change will reduce the dependencies we have.

## To-Do

- [x] Make sure that we convert all Treants from the old `mdsynthesis` format to the new `datreant` format, if we find old ones.
a) This will change the format from the `Sim` file to the `Treant` file. A conversion script is provided by the `datreant` devs.
b) The newest `datreant` version uses a dedicated `.datreant` folder instead of the `Treant` file.

**Comment by kain88-de** [comment]
currently, mdsynthesis pulls in: MDAnalysis, datreant-data, datreant, hdf5 and a lot of other smaller mdanalysis specific libraries. Switching to pure datreant would definitely lighten the number of dependencies that need to be installed.

**Comment by mimischi** [comment]
Indeed we currently do not utilize MDSynthesis nor MDAnalysis. We had plans to use some features from the latter in the future, but could definitely drop the dependencies for version 2.0, as long as we don't need them.
